[cicd_cmake_multi_platform.yml] temporary disable platforms: win10_cl & win11_cl
With cl.exe compiler complains due to the false positive:
`error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'`

win11_cl_Debug | CC=cl CXX=cl | windows-latest
https://github.com/WANDEX/algorithms/actions/runs/27026958722/job/79769292280#step:24:244

win10_cl_Debug | CC=cl CXX=cl | windows-2022
https://github.com/WANDEX/algorithms/actions/runs/27026958722/job/79769292291#step:24:244